### ISSUE TITLE
Build error when running ./configure

### ISSUE THREAD

**Issue by 009988jk** [zhouh/WCC-Segmentation#1]
Hello, thanks a lot for your uploading.
When I was compiling the code, after I run './configure', following errors happened:
`CMake Error at cmake/FindEigen3.cmake:33 (file):
  file failed to open for reading (No such file or directory):

    /home/test/WCC-Segmentation-master/segmenter/eigen//Eigen/src/Core/util/Macros.h
Call Stack (most recent call first):
  cmake/FindEigen3.cmake:59 (_eigen3_check_version)
  CMakeLists.txt:44 (find_package)`

I have installed cmake, boost and glog, but I still get these errors. Can you give me some suggestion about how to deal with it?
Thanks a lot for your reply.

**Comment by luckistmaomao** [comment]
There is something wrong when we upload eigen directory. We updated it , you can try it again.

**Comment by 009988jk** [comment]
Thanks a lot for your reply and uploading! And I also found that you can solve this problem by modifying the CMakeList file, line 19 in the segmenter folder:
`set(EIGEN3_INCLUDE_DIR eigen/)`
Change the 'eigen/' to the Eigen include directory. 
However, I got another problem, that after model's training, there are no model files.
When model training, the info saying:
`2018-05-08 10:15:53 [info] going to write parameters to file: ./model/model_50_08-05-2018 10:15.bin`
But when training was done, there are no model files anywhere. The corpus is the sample training data in the data directory. Could you give me any suggestion about handling this problem?
Thanks a lot for your assistance.

**Comment by 009988jk** [comment]
Now everything is OK, thank you very much, it's  a great work!
